version: "3.6"

services:
  backend-prd:
    build: 
      context: ./backend
      dockerfile: Dockerfile-prd
    volumes:
      - './backend:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - mysql
  
  frontend-prd:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prd
    environment:
      - NODE_ENV=production
    depends_on:
      - backend-prd

  nginx-prd:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile-prd
    ports:
      - 80:80
    depends_on:
      - backend-prd
      - frontend-prd
  
  mysql:
    build:
      context: ./db
      dockerfile: Dockerfile