#version: "3"

#services: 
#  app: 
#    build: .
#    command: yarn start
#    ports: 
#      - "3003:3003"
#    volumes: 
#      - .:/usr/app

version: "3"

services:
  db:
    build: ./db
  backend:
    build: ./backend
    ports:
      - "3003:3003"
    depends_on:
      - db
    restart: on-failure
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
